spring:
  application:
    name: adminboot

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: malldbuser
    password: malldbuser
    url: jdbc:mariadb://localhost:3306/malldb


    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 10000

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      location: D:\upload
      max-file-size: 2MB
      max-request-size: 20MB

logging:
  level:
    com.zaxxer: info
    org.springframework: info


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.example.adminboot.**.dto

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

board:
  upload: D:\upload\attach
